export const FETCH_MEDIA_REQUEST = 'FETCH_MEDIA_REQUEST';
export const FETCH_MEDIA_SUCCESS = 'FETCH_MEDIA_SUCCESS';
export const FETCH_MEDIA_FAILURE = 'FETCH_MEDIA_FAILURE';

export const SAVE_MEDIA_REQUEST = 'SAVE_MEDIA_REQUEST';
export const SAVE_MEDIA_SUCCESS = 'SAVE_MEDIA_SUCCESS';
export const SAVE_MEDIA_FAILURE = 'SAVE_MEDIA_FAILURE';
